COLUMNS = 7
ROWS = 6

WIN_CONDITION = 4

"""tree search"""
C_UBC = 10
C_PUCT = 3
DEFAULT_TEMP = 1
DEFAULT_ITERATIONS = 50

DEFAULT_STRUCTURE = 'structure1'
DEFAULT_TRAINING_TABLE = 'training_data'

DEFAULT_LEARNING_RATE = 0.0001
DEFAULT_BATCH_SIZE = 256
DEFAULT_EPOCHS = 1
DEFAULT_THRESHOLD = 0

"""GUI"""
SQUARE_SIZE = 64

"""database"""
HOST_NAME = 'localhost'
USER_NAME = 'root'
PASSWORD = 'password'
DATABASE = 'connect4'
