"""Tree Search"""
C_UBC = 10
C_PUCT = 3
DEFAULT_TEMP = 1
DEFAULT_ITERATIONS = 50

"""GUI"""
SQUARE_SIZE = 64

"""Database"""
HOST_NAME = 'localhost'
USER_NAME = 'root'
PASSWORD = 'password'
DATABASE = 'connect4'

"""Neural Network"""
DEFAULT_STRUCTURE = 'model0'

"""Training"""
DEFAULT_TRAINING_TABLE = 'training_data'

DEFAULT_LEARNING_RATE = 0.0001
DEFAULT_BATCH_SIZE = 256
DEFAULT_EPOCHS = 1
DEFAULT_THRESHOLD = 0
DEFAULT_TRAINING_NOISE = 0.5

"""Game"""
# CHANGE DEFAULT_STRUCTURE AND DEFAULT_TRAINING_TABLE WHEN CHANGING COLUMNS OR ROWS!
COLUMNS = 7
ROWS = 6
WIN_CONDITION = 4
